import '../auth/token_provider.dart';
import '../errors.dart';
import '../schema/schema.dart';

/// How mongobase stores and reads your data.
enum MongobaseMode {
  /// Keep a full local SQLite replica. Reads are instant, writes work with no
  /// network and upload when it returns. Costs a few MB of storage and one
  /// background sync loop.
  offline,

  /// No local database — every read and write goes straight to your backend.
  /// Simpler and always fresh, but nothing works without a connection.
  online,
}

/// Configuration for `Mongobase.init`.
///
/// One URL — your deployed backend — and a way to get the user's JWT.
class MongobaseConfig {
  MongobaseConfig({
    required this.apiUrl,
    required this.tokenProvider,
    required this.schema,
    this.mode = MongobaseMode.offline,
    this.realtime = true,
    this.realtimeCollections,
    this.syncInterval = const Duration(seconds: 5),
    this.pollInterval = const Duration(seconds: 5),
    this.autoSync = true,
    this.logWrites = false,
  }) {
    _validateUrl(apiUrl, 'apiUrl', example: 'https://your-backend.example.com');

    final unknown = realtimeCollections
        ?.where((name) => !schema.collections.containsKey(name))
        .toList();
    if (unknown != null && unknown.isNotEmpty) {
      throw ConfigurationException(
        'realtimeCollections names collections that are not in the schema: '
        '${unknown.join(', ')}.',
        hint: 'Declared collections: ${schema.collections.keys.join(', ')}.',
      );
    }
  }

  /// Root URL of the backend generated by `dart run mongobase:setup`,
  /// without a trailing slash — routes are appended (`/push`, `/pull`, ...).
  final String apiUrl;

  /// Supplies the user's JWT. See [TokenProvider] for provider recipes.
  final TokenProvider tokenProvider;

  /// The collection schema, usually the generated `mongobaseSchema` from
  /// `lib/mongobase_schema.g.dart`.
  final MongobaseSchema schema;

  /// Offline-first (default) or straight-to-backend. See [MongobaseMode].
  final MongobaseMode mode;

  /// Keep a live connection to the backend so changes arrive the moment they
  /// happen, instead of on the next poll.
  ///
  /// Requires a host that allows long-lived responses — a container works,
  /// short-lived serverless functions time the stream out. mongobase falls
  /// back to polling automatically whenever the stream is down, so leaving
  /// this on is safe everywhere.
  final bool realtime;

  /// Restrict realtime to these collections. Null means every collection in
  /// the schema.
  ///
  /// Worth setting when only part of your data needs to be live: a smaller
  /// subscription means fewer wakeups on the device and less work on the
  /// server.
  final Set<String>? realtimeCollections;

  /// How often the offline sync engine reconciles with the backend while
  /// everything is healthy. Failures back off exponentially from here.
  final Duration syncInterval;

  /// How often an online-mode `watch()` re-runs its query when realtime is
  /// unavailable.
  final Duration pollInterval;

  /// When false, nothing syncs until you call `Mongobase.instance.syncNow()`.
  /// Offline mode only — reads and writes still work against local data.
  final bool autoSync;

  /// When true, logs each uploaded write batch (for debugging sync issues).
  final bool logWrites;

  /// Collections the realtime channel should subscribe to.
  List<String> get subscribedCollections =>
      (realtimeCollections ?? schema.collections.keys.toSet()).toList()..sort();

  static void _validateUrl(String value, String field,
      {required String example}) {
    final uri = Uri.tryParse(value);
    final isHttp =
        uri != null && (uri.isScheme('https') || uri.isScheme('http'));
    if (!isHttp || uri.host.isEmpty) {
      throw ConfigurationException(
        '$field is not a valid URL: "$value".',
        hint: 'Expected something like $example. '
            'Run `dart run mongobase:setup` to configure the project.',
      );
    }
    if (value.endsWith('/')) {
      throw ConfigurationException(
        '$field must not end with a slash: "$value".',
        hint: 'Use $example — mongobase appends the routes itself.',
      );
    }
    if (uri.isScheme('http') &&
        uri.host != 'localhost' &&
        uri.host != '127.0.0.1' &&
        uri.host != '10.0.2.2') {
      throw ConfigurationException(
        '$field uses plain http on a non-local host: "$value".',
        hint: 'Use https for anything other than localhost / the Android '
            'emulator host (10.0.2.2).',
      );
    }
  }
}
