import '../auth/token_provider.dart';
import '../errors.dart';
import '../schema/schema.dart';

/// Configuration for [MongoEasy.init].
class MongoEasyConfig {
  MongoEasyConfig({
    required this.powersyncUrl,
    required this.uploadUrl,
    required this.tokenProvider,
    required this.schema,
    this.logWrites = false,
  }) {
    _validateUrl(powersyncUrl, 'powersyncUrl',
        example: 'https://<instance-id>.powersync.journeyapps.com');
    _validateUrl(uploadUrl, 'uploadUrl',
        example: 'https://your-backend.example.com/api/upload');
  }

  /// Your PowerSync instance URL (from the PowerSync dashboard).
  final String powersyncUrl;

  /// The deployed write-upload endpoint generated by
  /// `dart run mongo_easy:setup`.
  final String uploadUrl;

  /// Supplies the user's JWT. See [TokenProvider] for provider recipes.
  final TokenProvider tokenProvider;

  /// The collection schema, usually the generated `mongoEasySchema` from
  /// `lib/mongo_easy_schema.g.dart`.
  final MongoEasySchema schema;

  /// When true, logs each uploaded write batch (for debugging sync issues).
  final bool logWrites;

  static void _validateUrl(String value, String field,
      {required String example}) {
    final uri = Uri.tryParse(value);
    final isHttp =
        uri != null && (uri.isScheme('https') || uri.isScheme('http'));
    if (!isHttp || uri.host.isEmpty) {
      throw ConfigurationException(
        '$field is not a valid URL: "$value".',
        hint: 'Expected something like $example. '
            'Run `dart run mongo_easy:setup` to configure the project.',
      );
    }
    if (uri.isScheme('http') &&
        uri.host != 'localhost' &&
        uri.host != '127.0.0.1' &&
        uri.host != '10.0.2.2') {
      throw ConfigurationException(
        '$field uses plain http on a non-local host: "$value".',
        hint: 'Use https for anything other than localhost / the Android '
            'emulator host (10.0.2.2).',
      );
    }
  }
}
