import 'package:path/path.dart' as p;
import 'package:path_provider/path_provider.dart';
import 'package:powersync/powersync.dart' as ps;

import '../auth/jwt_utils.dart';
import '../errors.dart';
import '../sync/connector.dart';
import 'collection.dart';
import 'config.dart';
import 'powersync_executor.dart';
import 'powersync_schema.dart';
import 'sql_executor.dart';

/// The mongo_easy client. One line to initialize, Firestore-style collections
/// everywhere else:
///
/// ```dart
/// await MongoEasy.init(MongoEasyConfig(
///   powersyncUrl: 'https://<instance>.powersync.journeyapps.com',
///   uploadUrl: 'https://<your-fn>.vercel.app/api/upload',
///   tokenProvider: TokenProvider(() async => auth.currentJwt),
///   schema: mongoEasySchema, // generated by `dart run mongo_easy:setup`
/// ));
///
/// final todos = MongoEasy.collection('todos');
/// ```
class MongoEasy {
  MongoEasy._(this._config, this._db, this._connector, this._executor);

  static MongoEasy? _instance;

  final MongoEasyConfig _config;
  final ps.PowerSyncDatabase _db;
  final MongoEasyConnector _connector;
  final SqlExecutor _executor;

  /// The initialized client.
  ///
  /// Throws [NotInitializedException] before [init] completes.
  static MongoEasy get instance {
    final instance = _instance;
    if (instance == null) throw const NotInitializedException();
    return instance;
  }

  /// Whether [init] has completed.
  static bool get isInitialized => _instance != null;

  /// Opens the local database (offline-first) and starts syncing with
  /// MongoDB Atlas through PowerSync.
  ///
  /// Safe to call at app startup while offline — sync begins automatically
  /// once connectivity and a token are available.
  ///
  /// [databasePath] overrides where the local SQLite file is stored; by
  /// default it lives in the application support directory.
  static Future<MongoEasy> init(MongoEasyConfig config,
      {String? databasePath}) async {
    if (_instance != null) {
      throw const ConfigurationException(
        'MongoEasy.init() was called twice.',
        hint: 'Call init once at startup. For a clean re-init in tests, '
            'call `await MongoEasy.close()` first.',
      );
    }

    final path = databasePath ??
        p.join((await getApplicationSupportDirectory()).path, 'mongo_easy.db');

    final db = ps.PowerSyncDatabase(
      schema: config.schema.toPowerSyncSchema(),
      path: path,
    );
    await db.initialize();

    final connector = MongoEasyConnector(config);
    await db.connect(connector: connector);

    final instance = MongoEasy._(config, db, connector, PowerSyncExecutor(db));
    _instance = instance;
    return instance;
  }

  /// A Firestore-style handle on [name]. The collection must be declared in
  /// the schema (`mongo_easy.yaml`).
  static MongoCollection collection(String name) =>
      instance.getCollection(name);

  /// Instance form of [collection].
  MongoCollection getCollection(String name) {
    final schema = _config.schema.collection(name);
    return MongoCollection(
      _executor,
      schema,
      currentUserId: _requireUserId,
      newId: () => ps.uuid.v4(),
    );
  }

  /// The signed-in user's id (JWT `sub`), or `null` when signed out or not
  /// yet connected.
  String? get currentUserId => _connector.currentUserId;

  /// Live connection/sync status (connected, downloading, uploading, ...).
  Stream<ps.SyncStatus> get statusStream => _db.statusStream;

  /// Current connection/sync status snapshot.
  ps.SyncStatus get status => _db.currentStatus;

  /// Completes once the first full sync has finished — useful to gate a
  /// splash screen. Returns immediately on later app launches.
  Future<void> waitForFirstSync() => _db.waitForFirstSync();

  /// Re-evaluates credentials, e.g. right after sign-in or sign-out.
  Future<void> refreshToken() async {
    _connector.invalidateCredentials();
    await _db.connect(connector: _connector);
  }

  /// Deletes all local data. Call on sign-out to prevent the next user from
  /// seeing cached documents.
  Future<void> clearLocalData() async {
    await _db.disconnectAndClear();
  }

  /// Stops syncing and closes the local database.
  static Future<void> close() async {
    final instance = _instance;
    _instance = null;
    if (instance != null) {
      await instance._db.close();
    }
  }

  Future<String> _requireUserId() async {
    final cached = _connector.currentUserId;
    if (cached != null) return cached;

    // Not connected yet (e.g. offline right after startup) — derive the user
    // from the token directly.
    final token = await _config.tokenProvider.getToken();
    if (token == null || token.isEmpty) {
      throw const InvalidTokenException(
        'Cannot auto-fill the owner field: no user is signed in.',
        hint: 'Sign in before writing, or pass the owner field explicitly '
            'in the document.',
      );
    }
    return decodeJwt(token).subject;
  }
}
