import 'dart:async';

import 'package:path/path.dart' as p;
import 'package:path_provider/path_provider.dart';
import 'package:sqlite_async/sqlite_async.dart';
import 'package:uuid/uuid.dart';

import '../auth/jwt_utils.dart';
import '../errors.dart';
import '../query/local_query_runner.dart';
import '../query/query_runner.dart';
import '../query/remote_query_runner.dart';
import '../storage/storage.dart';
import '../store/local_store.dart';
import '../store/local_writer.dart';
import '../store/sqlite_executor.dart';
import '../sync/realtime_client.dart';
import '../sync/sync_api.dart';
import '../sync/sync_engine.dart';
import '../sync/sync_status.dart';
import 'collection.dart';
import 'config.dart';
import 'document_writer.dart';
import 'remote_writer.dart';

/// The onebase client. One line to initialize, Firestore-style collections
/// everywhere else:
///
/// ```dart
/// await Onebase.init(OnebaseConfig(
///   apiUrl: 'https://your-backend.example.com',
///   tokenProvider: TokenProvider(() async => auth.currentJwt),
///   schema: onebaseSchema, // generated by `dart run onebase:setup`
/// ));
///
/// final todos = Onebase.collection('todos');
/// ```
class Onebase {
  Onebase._(
    this._config,
    this._runner,
    this._writer, {
    SqliteDatabase? database,
    LocalStore? store,
    SyncEngine? engine,
    RealtimeClient? realtime,
    required SyncApi api,
  }) : _database = database,
       _store = store,
       _engine = engine,
       _realtime = realtime,
       _api = api;

  static Onebase? _instance;

  final OnebaseConfig _config;
  final QueryRunner _runner;
  final DocumentWriter _writer;
  final SyncApi _api;

  /// Offline mode only.
  final SqliteDatabase? _database;
  final LocalStore? _store;
  final SyncEngine? _engine;

  /// Present whenever realtime is enabled.
  final RealtimeClient? _realtime;

  final Uuid _uuid = const Uuid();
  String? _currentUserId;

  /// The initialized client.
  ///
  /// Throws [NotInitializedException] before [init] completes.
  static Onebase get instance {
    final instance = _instance;
    if (instance == null) throw const NotInitializedException();
    return instance;
  }

  /// Whether [init] has completed.
  static bool get isInitialized => _instance != null;

  /// Prepares the client for use.
  ///
  /// In offline mode (the default) this opens the local replica and starts
  /// syncing; it is safe to call while offline, since reads and writes work
  /// immediately against local data. In online mode it does no I/O at all.
  ///
  /// [databasePath] overrides where the SQLite file lives; by default it sits
  /// in the application support directory. Ignored in online mode.
  static Future<Onebase> init(
    OnebaseConfig config, {
    String? databasePath,
  }) async {
    if (_instance != null) {
      throw const ConfigurationException(
        'Onebase.init() was called twice.',
        hint:
            'Call init once at startup. For a clean re-init in tests, '
            'call `await Onebase.close()` first.',
      );
    }

    final api = SyncApi(
      baseUrl: config.apiUrl,
      tokenProvider: config.tokenProvider,
    );

    final realtime = config.realtime
        ? RealtimeClient(api: api, collections: config.subscribedCollections)
        : null;

    final Onebase instance;
    if (config.mode == OnebaseMode.online) {
      instance = Onebase._(
        config,
        RemoteQueryRunner(
          api,
          changes: realtime?.events.map((event) => event.collection),
          pollInterval: config.pollInterval,
        ),
        RemoteWriter(api),
        api: api,
        realtime: realtime,
      );
    } else {
      final path =
          databasePath ??
          p.join((await getApplicationSupportDirectory()).path, 'onebase.db');

      final database = SqliteDatabase(path: path);
      await database.initialize();

      final store = LocalStore(database, config.schema);
      await store.migrate();

      final engine = SyncEngine(
        store: store,
        api: api,
        schema: config.schema,
        interval: config.syncInterval,
      );

      instance = Onebase._(
        config,
        LocalQueryRunner(SqliteExecutor(database)),
        LocalWriter(store),
        database: database,
        store: store,
        engine: engine,
        realtime: realtime,
        api: api,
      );

      // A pushed change is applied straight to the replica, so watchers fire
      // within milliseconds. The periodic sync still runs and remains the
      // authority on the watermark, so nothing is missed if the stream drops.
      realtime?.events.listen((event) {
        unawaited(store.applyPull(event.collection, [event.document], null));
      });

      if (config.autoSync) engine.start();
    }

    _instance = instance;
    if (config.realtime) realtime!.start();
    return instance;
  }

  /// A Firestore-style handle on [name]. The collection must be declared in
  /// the schema (`onebase.yaml`).
  static MongoCollection collection(String name) =>
      instance.getCollection(name);

  /// Instance form of [collection].
  MongoCollection getCollection(String name) {
    final schema = _config.schema.collection(name);
    return MongoCollection(
      _runner,
      _writer,
      schema,
      currentUserId: _requireUserId,
      newId: () => _uuid.v4(),
    );
  }

  /// The mode this client was initialized in.
  OnebaseMode get mode => _config.mode;

  /// File storage:
  ///
  /// ```dart
  /// await Onebase.storage.ref('avatars/me.png').putData(bytes);
  /// ```
  ///
  /// Buckets are declared under `storage:` in `onebase.yaml`.
  static OnebaseStorage get storage => instance.getStorage();

  /// Instance form of [storage].
  OnebaseStorage getStorage() => OnebaseStorage(_api, _config.schema);

  /// The signed-in user's id (JWT `sub`), or `null` when signed out.
  String? get currentUserId => _currentUserId;

  /// Whether the realtime channel is currently connected. False when realtime
  /// is disabled, the stream dropped, or the host does not support it — in
  /// every case data still flows, just on the poll interval.
  bool get isRealtimeConnected => _realtime?.isConnected ?? false;

  /// Realtime connection state changes — drive a "live" badge from this.
  Stream<bool> get realtimeState =>
      _realtime?.connectionState ?? const Stream<bool>.empty();

  /// Live sync status. In online mode this reports auth state only, since
  /// there is no queue or replica to reconcile.
  Stream<SyncStatus> get statusStream =>
      _engine?.statusStream ?? const Stream<SyncStatus>.empty();

  /// Current sync status snapshot.
  SyncStatus get status => _engine?.status ?? const SyncStatus();

  /// Completes once the first successful sync has finished — useful to gate a
  /// splash screen on a fresh install. Returns immediately in online mode.
  Future<void> waitForFirstSync() async {
    final engine = _engine;
    if (engine == null) return;
    await engine.firstSync;
  }

  /// Runs one sync round trip immediately. Returns true when it succeeded,
  /// and always true in online mode (there is nothing to reconcile).
  /// Never throws — check [status] for the reason on failure.
  Future<bool> syncNow() async => await _engine?.syncNow() ?? true;

  /// Re-reads the token and reconnects, e.g. right after sign-in.
  Future<void> refreshToken() async {
    _currentUserId = null;
    await _requireUserIdOrNull();
    final realtime = _realtime;
    if (realtime != null) {
      await realtime.stop();
      realtime.start();
    }
    await _engine?.syncNow();
  }

  /// Deletes all local data. Call on sign-out so the next user cannot see
  /// cached documents. A no-op in online mode, which caches nothing.
  Future<void> clearLocalData() async {
    await _store?.clear();
    _currentUserId = null;
  }

  /// Stops syncing and releases everything.
  static Future<void> close() async {
    final instance = _instance;
    _instance = null;
    if (instance == null) return;
    await instance._realtime?.close();
    await instance._engine?.close();
    await instance._database?.close();
    instance._api.close();
  }

  Future<String?> _requireUserIdOrNull() async {
    final cached = _currentUserId;
    if (cached != null) return cached;
    final token = await _config.tokenProvider.getToken();
    if (token == null || token.isEmpty) return null;
    return _currentUserId = decodeJwt(token).subject;
  }

  Future<String> _requireUserId() async {
    final id = await _requireUserIdOrNull();
    if (id == null) {
      throw const InvalidTokenException(
        'Cannot auto-fill the owner field: no user is signed in.',
        hint:
            'Sign in before writing, or pass the owner field explicitly '
            'in the document.',
      );
    }
    return id;
  }
}
