import '../query/query_builder.dart';
import 'collection.dart';

/// A [MongoCollection] view that converts documents to and from a model [T].
class TypedCollection<T> {
  TypedCollection(
    this._collection, {
    required T Function(Map<String, Object?> json) fromJson,
    required Map<String, Object?> Function(T value) toJson,
  })  : _fromJson = fromJson,
        _toJson = toJson;

  final MongoCollection _collection;
  final T Function(Map<String, Object?> json) _fromJson;
  final Map<String, Object?> Function(T value) _toJson;

  /// Inserts [value] and returns its generated id.
  ///
  /// A `null` or absent `id` key in `toJson` output is ignored — ids are
  /// always generated by mongo_easy.
  Future<String> insert(T value) {
    final json = Map<String, Object?>.of(_toJson(value))..remove('id');
    return _collection.insert(json);
  }

  Future<void> update(String id, Map<String, Object?> changes) =>
      _collection.update(id, changes);

  Future<void> delete(String id) => _collection.delete(id);

  Future<T?> findById(String id) async {
    final document = await _collection.findById(id);
    return document == null ? null : _fromJson(document);
  }

  Future<List<T>> find() async =>
      [for (final document in await _collection.find()) _fromJson(document)];

  Future<T?> findOne() async {
    final document = await _collection.findOne();
    return document == null ? null : _fromJson(document);
  }

  Future<int> count() => _collection.count();

  Stream<List<T>> watch() => _collection
      .watch()
      .map((documents) => [for (final doc in documents) _fromJson(doc)]);

  /// Filtered typed query. See [MongoQuery.where] for operators.
  TypedQuery<T> where(
    String field, {
    Object? isEqualTo,
    Object? isNotEqualTo,
    Object? isGreaterThan,
    Object? isGreaterThanOrEqualTo,
    Object? isLessThan,
    Object? isLessThanOrEqualTo,
    List<Object>? whereIn,
    bool? isNull,
  }) {
    return TypedQuery<T>(
      _collection.where(
        field,
        isEqualTo: isEqualTo,
        isNotEqualTo: isNotEqualTo,
        isGreaterThan: isGreaterThan,
        isGreaterThanOrEqualTo: isGreaterThanOrEqualTo,
        isLessThan: isLessThan,
        isLessThanOrEqualTo: isLessThanOrEqualTo,
        whereIn: whereIn,
        isNull: isNull,
      ),
      _fromJson,
    );
  }

  TypedQuery<T> orderBy(String field, {bool descending = false}) =>
      TypedQuery<T>(
          _collection.orderBy(field, descending: descending), _fromJson);

  TypedQuery<T> limit(int count) =>
      TypedQuery<T>(_collection.limit(count), _fromJson);
}

/// A typed wrapper around [MongoQuery].
class TypedQuery<T> {
  TypedQuery(this._query, this._fromJson);

  final MongoQuery _query;
  final T Function(Map<String, Object?> json) _fromJson;

  TypedQuery<T> where(
    String field, {
    Object? isEqualTo,
    Object? isNotEqualTo,
    Object? isGreaterThan,
    Object? isGreaterThanOrEqualTo,
    Object? isLessThan,
    Object? isLessThanOrEqualTo,
    List<Object>? whereIn,
    bool? isNull,
  }) {
    return TypedQuery<T>(
      _query.where(
        field,
        isEqualTo: isEqualTo,
        isNotEqualTo: isNotEqualTo,
        isGreaterThan: isGreaterThan,
        isGreaterThanOrEqualTo: isGreaterThanOrEqualTo,
        isLessThan: isLessThan,
        isLessThanOrEqualTo: isLessThanOrEqualTo,
        whereIn: whereIn,
        isNull: isNull,
      ),
      _fromJson,
    );
  }

  TypedQuery<T> orderBy(String field, {bool descending = false}) =>
      TypedQuery<T>(_query.orderBy(field, descending: descending), _fromJson);

  TypedQuery<T> limit(int count) =>
      TypedQuery<T>(_query.limit(count), _fromJson);

  TypedQuery<T> offset(int count) =>
      TypedQuery<T>(_query.offset(count), _fromJson);

  Future<List<T>> find() async =>
      [for (final document in await _query.find()) _fromJson(document)];

  Future<T?> findOne() async {
    final document = await _query.findOne();
    return document == null ? null : _fromJson(document);
  }

  Future<int> count() => _query.count();

  Stream<List<T>> watch() => _query
      .watch()
      .map((documents) => [for (final doc in documents) _fromJson(doc)]);
}
