// GENERATED by `dart run onebase:setup` — do not edit.
// Source of truth: onebase.yaml
import 'package:onebase/onebase.dart';

/// The app schema, mirroring onebase.yaml.
final onebaseSchema = OnebaseSchema([
  MongoCollectionSchema(
    'family_members',
    fields: {
      'family_id': MongoFieldType.text,
      'user_id': MongoFieldType.text,
      'role': MongoFieldType.text,
    },
    shared: true,
    requiredFields: {'family_id', 'user_id'},
    model: 'FamilyMember',
  ),
  MongoCollectionSchema(
    'chores',
    fields: {
      'title': MongoFieldType.text,
      'family_id': MongoFieldType.text,
      'owner_id': MongoFieldType.text,
    },
    requiredFields: {'title', 'family_id'},
    model: 'Chore',
  ),
  MongoCollectionSchema(
    'family_settings',
    fields: {
      'family_id': MongoFieldType.text,
      'quiet_hours': MongoFieldType.text,
    },
    requiredFields: {'family_id'},
    model: 'FamilySetting',
  ),
  MongoCollectionSchema(
    'diaries',
    fields: {
      'family_id': MongoFieldType.text,
      'owner_id': MongoFieldType.text,
      'entry': MongoFieldType.text,
    },
    ownerField: 'owner_id',
    requiredFields: {'family_id', 'owner_id'},
    model: 'Diary',
  ),
  MongoCollectionSchema(
    'messages',
    fields: {
      'body': MongoFieldType.text,
      'family_id': MongoFieldType.text,
      'sent_at': MongoFieldType.datetime,
    },
    requiredFields: {'body', 'family_id'},
    model: 'Message',
  ),
  MongoCollectionSchema(
    'audit_log',
    fields: {
      'family_id': MongoFieldType.text,
      'message': MongoFieldType.text,
    },
    requiredFields: {'family_id', 'message'},
    model: 'AuditLog',
  ),
]);

/// Typed collections, ready to use:
///
/// ```dart
/// final familyMembers = await OnebaseDb.familyMembers.find();
/// ```
abstract final class OnebaseDb {
  static TypedCollection<FamilyMember> get familyMembers =>
      Onebase.collection('family_members')
          .withConverter<FamilyMember>(
            fromJson: FamilyMember.fromJson,
            toJson: (value) => value.toJson(),
          );

  static TypedCollection<Chore> get chores =>
      Onebase.collection('chores')
          .withConverter<Chore>(
            fromJson: Chore.fromJson,
            toJson: (value) => value.toJson(),
          );

  static TypedCollection<FamilySetting> get familySettings =>
      Onebase.collection('family_settings')
          .withConverter<FamilySetting>(
            fromJson: FamilySetting.fromJson,
            toJson: (value) => value.toJson(),
          );

  static TypedCollection<Diary> get diaries =>
      Onebase.collection('diaries')
          .withConverter<Diary>(
            fromJson: Diary.fromJson,
            toJson: (value) => value.toJson(),
          );

  static TypedCollection<Message> get messages =>
      Onebase.collection('messages')
          .withConverter<Message>(
            fromJson: Message.fromJson,
            toJson: (value) => value.toJson(),
          );

  static TypedCollection<AuditLog> get auditLog =>
      Onebase.collection('audit_log')
          .withConverter<AuditLog>(
            fromJson: AuditLog.fromJson,
            toJson: (value) => value.toJson(),
          );

}

/// A document in `family_members`.
class FamilyMember {
  const FamilyMember({
    this.id = '',
    required this.familyId,
    required this.userId,
    this.role,
  });

  /// Empty until the document has been inserted — onebase
  /// assigns the id and `insert` returns it.
  final String id;
  final String familyId;
  final String userId;
  final String? role;

  factory FamilyMember.fromJson(Map<String, Object?> json) {
    return FamilyMember(
      id: json['id'] as String? ?? '',
      familyId: json['family_id'] as String? ?? _missing('family_id'),
      userId: json['user_id'] as String? ?? _missing('user_id'),
      role: json['role'] as String?,
    );
  }

  Map<String, Object?> toJson() => {
        if (id.isNotEmpty) 'id': id,
        'family_id': familyId,
        'user_id': userId,
        if (role != null) 'role': role,
      };

  /// Returns a copy with the given fields replaced. Passing
  /// null leaves a field unchanged.
  FamilyMember copyWith({
    String? id,
    String? familyId,
    String? userId,
    String? role,
  }) {
    return FamilyMember(
      id: id ?? this.id,
      familyId: familyId ?? this.familyId,
      userId: userId ?? this.userId,
      role: role ?? this.role,
    );
  }

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FamilyMember &&
          id == other.id &&
          familyId == other.familyId &&
          userId == other.userId &&
          role == other.role
;

  @override
  int get hashCode => Object.hashAll([id, familyId, userId, role]);

  @override
  String toString() => 'FamilyMember(${toJson()})';
}

/// A document in `chores`.
class Chore {
  const Chore({
    this.id = '',
    required this.title,
    required this.familyId,
    this.ownerId,
  });

  /// Empty until the document has been inserted — onebase
  /// assigns the id and `insert` returns it.
  final String id;
  final String title;
  final String familyId;
  final String? ownerId;

  factory Chore.fromJson(Map<String, Object?> json) {
    return Chore(
      id: json['id'] as String? ?? '',
      title: json['title'] as String? ?? _missing('title'),
      familyId: json['family_id'] as String? ?? _missing('family_id'),
      ownerId: json['owner_id'] as String?,
    );
  }

  Map<String, Object?> toJson() => {
        if (id.isNotEmpty) 'id': id,
        'title': title,
        'family_id': familyId,
        if (ownerId != null) 'owner_id': ownerId,
      };

  /// Returns a copy with the given fields replaced. Passing
  /// null leaves a field unchanged.
  Chore copyWith({
    String? id,
    String? title,
    String? familyId,
    String? ownerId,
  }) {
    return Chore(
      id: id ?? this.id,
      title: title ?? this.title,
      familyId: familyId ?? this.familyId,
      ownerId: ownerId ?? this.ownerId,
    );
  }

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Chore &&
          id == other.id &&
          title == other.title &&
          familyId == other.familyId &&
          ownerId == other.ownerId
;

  @override
  int get hashCode => Object.hashAll([id, title, familyId, ownerId]);

  @override
  String toString() => 'Chore(${toJson()})';
}

/// A document in `family_settings`.
class FamilySetting {
  const FamilySetting({
    this.id = '',
    required this.familyId,
    this.quietHours,
  });

  /// Empty until the document has been inserted — onebase
  /// assigns the id and `insert` returns it.
  final String id;
  final String familyId;
  final String? quietHours;

  factory FamilySetting.fromJson(Map<String, Object?> json) {
    return FamilySetting(
      id: json['id'] as String? ?? '',
      familyId: json['family_id'] as String? ?? _missing('family_id'),
      quietHours: json['quiet_hours'] as String?,
    );
  }

  Map<String, Object?> toJson() => {
        if (id.isNotEmpty) 'id': id,
        'family_id': familyId,
        if (quietHours != null) 'quiet_hours': quietHours,
      };

  /// Returns a copy with the given fields replaced. Passing
  /// null leaves a field unchanged.
  FamilySetting copyWith({
    String? id,
    String? familyId,
    String? quietHours,
  }) {
    return FamilySetting(
      id: id ?? this.id,
      familyId: familyId ?? this.familyId,
      quietHours: quietHours ?? this.quietHours,
    );
  }

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FamilySetting &&
          id == other.id &&
          familyId == other.familyId &&
          quietHours == other.quietHours
;

  @override
  int get hashCode => Object.hashAll([id, familyId, quietHours]);

  @override
  String toString() => 'FamilySetting(${toJson()})';
}

/// A document in `diaries`.
class Diary {
  const Diary({
    this.id = '',
    required this.familyId,
    required this.ownerId,
    this.entry,
  });

  /// Empty until the document has been inserted — onebase
  /// assigns the id and `insert` returns it.
  final String id;
  final String familyId;
  final String ownerId;
  final String? entry;

  factory Diary.fromJson(Map<String, Object?> json) {
    return Diary(
      id: json['id'] as String? ?? '',
      familyId: json['family_id'] as String? ?? _missing('family_id'),
      ownerId: json['owner_id'] as String? ?? _missing('owner_id'),
      entry: json['entry'] as String?,
    );
  }

  Map<String, Object?> toJson() => {
        if (id.isNotEmpty) 'id': id,
        'family_id': familyId,
        'owner_id': ownerId,
        if (entry != null) 'entry': entry,
      };

  /// Returns a copy with the given fields replaced. Passing
  /// null leaves a field unchanged.
  Diary copyWith({
    String? id,
    String? familyId,
    String? ownerId,
    String? entry,
  }) {
    return Diary(
      id: id ?? this.id,
      familyId: familyId ?? this.familyId,
      ownerId: ownerId ?? this.ownerId,
      entry: entry ?? this.entry,
    );
  }

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Diary &&
          id == other.id &&
          familyId == other.familyId &&
          ownerId == other.ownerId &&
          entry == other.entry
;

  @override
  int get hashCode => Object.hashAll([id, familyId, ownerId, entry]);

  @override
  String toString() => 'Diary(${toJson()})';
}

/// A document in `messages`.
class Message {
  const Message({
    this.id = '',
    required this.body,
    required this.familyId,
    this.sentAt,
  });

  /// Empty until the document has been inserted — onebase
  /// assigns the id and `insert` returns it.
  final String id;
  final String body;
  final String familyId;
  final DateTime? sentAt;

  factory Message.fromJson(Map<String, Object?> json) {
    return Message(
      id: json['id'] as String? ?? '',
      body: json['body'] as String? ?? _missing('body'),
      familyId: json['family_id'] as String? ?? _missing('family_id'),
      sentAt: json['sent_at'] as DateTime?,
    );
  }

  Map<String, Object?> toJson() => {
        if (id.isNotEmpty) 'id': id,
        'body': body,
        'family_id': familyId,
        if (sentAt != null) 'sent_at': sentAt,
      };

  /// Returns a copy with the given fields replaced. Passing
  /// null leaves a field unchanged.
  Message copyWith({
    String? id,
    String? body,
    String? familyId,
    DateTime? sentAt,
  }) {
    return Message(
      id: id ?? this.id,
      body: body ?? this.body,
      familyId: familyId ?? this.familyId,
      sentAt: sentAt ?? this.sentAt,
    );
  }

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Message &&
          id == other.id &&
          body == other.body &&
          familyId == other.familyId &&
          sentAt == other.sentAt
;

  @override
  int get hashCode => Object.hashAll([id, body, familyId, sentAt]);

  @override
  String toString() => 'Message(${toJson()})';
}

/// A document in `audit_log`.
class AuditLog {
  const AuditLog({
    this.id = '',
    required this.familyId,
    required this.message,
  });

  /// Empty until the document has been inserted — onebase
  /// assigns the id and `insert` returns it.
  final String id;
  final String familyId;
  final String message;

  factory AuditLog.fromJson(Map<String, Object?> json) {
    return AuditLog(
      id: json['id'] as String? ?? '',
      familyId: json['family_id'] as String? ?? _missing('family_id'),
      message: json['message'] as String? ?? _missing('message'),
    );
  }

  Map<String, Object?> toJson() => {
        if (id.isNotEmpty) 'id': id,
        'family_id': familyId,
        'message': message,
      };

  /// Returns a copy with the given fields replaced. Passing
  /// null leaves a field unchanged.
  AuditLog copyWith({
    String? id,
    String? familyId,
    String? message,
  }) {
    return AuditLog(
      id: id ?? this.id,
      familyId: familyId ?? this.familyId,
      message: message ?? this.message,
    );
  }

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AuditLog &&
          id == other.id &&
          familyId == other.familyId &&
          message == other.message
;

  @override
  int get hashCode => Object.hashAll([id, familyId, message]);

  @override
  String toString() => 'AuditLog(${toJson()})';
}

/// Thrown when a document is missing a field the schema marks required.
Never _missing(String field) {
  throw StateError(
    'onebase: document is missing required field "$field". '
    'Either make it optional in onebase.yaml (drop the trailing !) '
    'or backfill the existing documents.',
  );
}
