import '../schema/schema.dart';

/// Generates `lib/onebase_schema.g.dart`: the Dart mirror of
/// `onebase.yaml`, a typed model per collection, and typed accessors.
///
/// The point is that you never hand-write a model or wire up a converter —
/// `OnebaseDb.todos` already returns `Todo`.
String generateDartSchema(OnebaseSchema schema) {
  final buffer = StringBuffer()
    ..writeln('// GENERATED by `dart run onebase:setup` — do not edit.')
    ..writeln('// Source of truth: onebase.yaml')
    ..writeln("import 'package:onebase/onebase.dart';")
    ..writeln()
    ..writeln('/// The app schema, mirroring onebase.yaml.')
    ..writeln('final onebaseSchema = OnebaseSchema([');

  for (final collection in schema.collections.values) {
    buffer
      ..writeln('  MongoCollectionSchema(')
      ..writeln("    '${collection.name}',")
      ..writeln('    fields: {');
    for (final MapEntry(key: field, value: type) in collection.fields.entries) {
      buffer.writeln("      '$field': MongoFieldType.${type.name},");
    }
    buffer.writeln('    },');
    if (collection.ownerField != null) {
      buffer.writeln("    ownerField: '${collection.ownerField}',");
    }
    if (collection.shared) buffer.writeln('    shared: true,');
    if (collection.requiredFields.isNotEmpty) {
      final names =
          collection.requiredFields.map((field) => "'$field'").join(', ');
      buffer.writeln('    requiredFields: {$names},');
    }
    buffer
      ..writeln("    model: '${collection.model}',")
      ..writeln('  ),');
  }
  buffer
    ..writeln(']);')
    ..writeln()
    ..writeln('/// Typed collections, ready to use:')
    ..writeln('///')
    ..writeln('/// ```dart')
    ..writeln('/// final ${_firstAccessor(schema)} = '
        'await OnebaseDb.${_firstAccessor(schema)}.find();')
    ..writeln('/// ```')
    ..writeln('abstract final class OnebaseDb {');

  for (final collection in schema.collections.values) {
    final model = collection.model;
    buffer
      ..writeln('  static TypedCollection<$model> get ${collection.name} =>')
      ..writeln("      Onebase.collection('${collection.name}')")
      ..writeln('          .withConverter<$model>(')
      ..writeln('            fromJson: $model.fromJson,')
      ..writeln('            toJson: (value) => value.toJson(),')
      ..writeln('          );')
      ..writeln();
  }
  buffer.writeln('}');

  for (final collection in schema.collections.values) {
    buffer
      ..writeln()
      ..write(_model(collection));
  }

  final hasRequired = schema.collections.values
      .any((collection) => collection.requiredFields.isNotEmpty);
  if (hasRequired) buffer.write(_missingHelper);

  return buffer.toString();
}

String _firstAccessor(OnebaseSchema schema) => schema.collections.keys.first;

String _model(MongoCollectionSchema collection) {
  final model = collection.model;
  final fields = collection.fields.entries.toList();
  final buffer = StringBuffer()
    ..writeln('/// A document in `${collection.name}`.')
    ..writeln('class $model {')
    ..writeln('  const $model({')
    ..writeln("    this.id = '',");

  for (final MapEntry(key: field, value: _) in fields) {
    final name = _dartField(field);
    buffer.writeln(collection.isRequired(field)
        ? '    required this.$name,'
        : '    this.$name,');
  }

  buffer
    ..writeln('  });')
    ..writeln()
    ..writeln('  /// Empty until the document has been inserted — onebase')
    ..writeln('  /// assigns the id and `insert` returns it.')
    ..writeln('  final String id;');

  for (final MapEntry(key: field, value: type) in fields) {
    final dartType = _dartType(type);
    final nullable = collection.isRequired(field) ? '' : '?';
    if (type == MongoFieldType.json) {
      buffer
        ..writeln()
        ..writeln('  /// A json field: a `Map` or `List`, depending on what')
        ..writeln('  /// you store. Cast it where you use it.');
    }
    buffer.writeln('  final $dartType$nullable ${_dartField(field)};');
  }

  // fromJson
  buffer
    ..writeln()
    ..writeln('  factory $model.fromJson(Map<String, Object?> json) {')
    ..writeln('    return $model(')
    ..writeln("      id: json['id'] as String? ?? '',");
  for (final MapEntry(key: field, value: type) in fields) {
    final accessor = "json['$field']";
    final cast = _fromJsonExpression(accessor, type);
    if (collection.isRequired(field)) {
      buffer.writeln('      ${_dartField(field)}: $cast '
          "?? _missing('$field'),");
    } else {
      buffer.writeln('      ${_dartField(field)}: $cast,');
    }
  }
  buffer
    ..writeln('    );')
    ..writeln('  }');

  // toJson
  buffer
    ..writeln()
    ..writeln('  Map<String, Object?> toJson() => {')
    ..writeln("        if (id.isNotEmpty) 'id': id,");
  for (final MapEntry(key: field, value: _) in fields) {
    final name = _dartField(field);
    buffer.writeln(collection.isRequired(field)
        ? "        '$field': $name,"
        : "        if ($name != null) '$field': $name,");
  }
  buffer.writeln('      };');

  // copyWith
  buffer
    ..writeln()
    ..writeln('  /// Returns a copy with the given fields replaced. Passing')
    ..writeln('  /// null leaves a field unchanged.')
    ..writeln('  $model copyWith({')
    ..writeln('    String? id,');
  for (final MapEntry(key: field, value: type) in fields) {
    buffer.writeln('    ${_dartType(type)}? ${_dartField(field)},');
  }
  buffer
    ..writeln('  }) {')
    ..writeln('    return $model(')
    ..writeln('      id: id ?? this.id,');
  for (final MapEntry(key: field, value: _) in fields) {
    final name = _dartField(field);
    buffer.writeln('      $name: $name ?? this.$name,');
  }
  buffer
    ..writeln('    );')
    ..writeln('  }');

  // equality
  final names = ['id', for (final entry in fields) _dartField(entry.key)];
  buffer
    ..writeln()
    ..writeln('  @override')
    ..writeln('  bool operator ==(Object other) =>')
    ..writeln('      identical(this, other) ||')
    ..writeln('      other is $model &&')
    ..writeln(
        names.map((name) => '          $name == other.$name').join(' &&\n'))
    ..writeln(';')
    ..writeln()
    ..writeln('  @override')
    ..writeln('  int get hashCode => Object.hashAll([${names.join(', ')}]);')
    ..writeln()
    ..writeln('  @override')
    ..writeln("  String toString() => '$model(\${toJson()})';")
    ..writeln('}');

  return buffer.toString();
}

/// Fields are declared snake_case in YAML; Dart wants lowerCamelCase.
String _dartField(String field) {
  final parts = field.split('_').where((part) => part.isNotEmpty).toList();
  if (parts.isEmpty) return field;
  return parts.first +
      parts
          .skip(1)
          .map((part) => part[0].toUpperCase() + part.substring(1))
          .join();
}

String _dartType(MongoFieldType type) => switch (type) {
      MongoFieldType.text => 'String',
      MongoFieldType.int => 'int',
      MongoFieldType.double => 'double',
      MongoFieldType.bool => 'bool',
      MongoFieldType.datetime => 'DateTime',
      MongoFieldType.json => 'Object',
    };

/// onebase already decodes values by type before a model sees them, so
/// these are plain casts — except `double`, which SQLite may hand back as an
/// `int` when the stored value happens to be whole.
String _fromJsonExpression(String accessor, MongoFieldType type) =>
    switch (type) {
      MongoFieldType.double => '($accessor as num?)?.toDouble()',
      MongoFieldType.text => '$accessor as String?',
      MongoFieldType.int => '$accessor as int?',
      MongoFieldType.bool => '$accessor as bool?',
      MongoFieldType.datetime => '$accessor as DateTime?',
      MongoFieldType.json => accessor,
    };

/// Emitted once per generated file, used by required fields in `fromJson`.
const _missingHelper = '''

/// Thrown when a document is missing a field the schema marks required.
Never _missing(String field) {
  throw StateError(
    'onebase: document is missing required field "\$field". '
    'Either make it optional in onebase.yaml (drop the trailing !) '
    'or backfill the existing documents.',
  );
}
''';
