/// Generates `lib/mongo_easy_endpoints.g.dart` after an automated setup, so
/// the app config needs zero copy-pasting.
String generateEndpointsDart({
  required String powersyncUrl,
  required String uploadUrl,
  required String tokenUrl,
}) {
  return '''
// GENERATED by `dart run mongo_easy:setup` — do not edit.
// Re-run setup to refresh after redeploying.

/// Endpoints provisioned by mongo_easy setup.
abstract final class MongoEasyEndpoints {
  static const powersyncUrl = '$powersyncUrl';
  static const uploadUrl = '$uploadUrl';

  /// Dev-only email login endpoint (AUTH_MODE=dev).
  static const tokenUrl = '$tokenUrl';
}
''';
}
