import '../schema/schema.dart';

/// Generates the PowerSync Sync Streams YAML (edition 3) for [schema].
///
/// Per-user collections filter on `auth.user_id()` (the JWT `sub` claim) —
/// isolation is enforced by the PowerSync Service, never client-side.
/// MongoDB's `_id` is aliased to `id`, which PowerSync requires.
String generateSyncStreamsYaml(MongoEasySchema schema) {
  final buffer = StringBuffer()
    ..writeln('# Generated by `dart run mongo_easy:setup` — paste into your')
    ..writeln('# PowerSync instance (Dashboard → Sync Streams) or deploy with')
    ..writeln(
        '# the PowerSync CLI. Re-run setup after editing mongo_easy.yaml.')
    ..writeln('config:')
    ..writeln('  edition: 3')
    ..writeln()
    ..writeln('streams:');

  for (final collection in schema.collections.values) {
    buffer
      ..writeln('  ${collection.name}:')
      ..writeln('    auto_subscribe: true');
    if (collection.shared) {
      buffer.writeln('    query: SELECT *, _id as id FROM ${collection.name}');
    } else {
      buffer.writeln('    query: SELECT *, _id as id FROM ${collection.name} '
          'WHERE ${collection.ownerField} = auth.user_id()');
    }
  }

  return buffer.toString();
}
