import '../schema/schema.dart';

/// Generates `lib/mongo_easy_schema.g.dart` — the Dart mirror of
/// `mongo_easy.yaml` that the app passes to `MongoEasy.init`.
String generateDartSchema(MongoEasySchema schema) {
  final buffer = StringBuffer()
    ..writeln('// GENERATED by `dart run mongo_easy:setup` — do not edit.')
    ..writeln('// Source of truth: mongo_easy.yaml')
    ..writeln("import 'package:mongo_easy/mongo_easy.dart';")
    ..writeln()
    ..writeln('/// The app schema, mirroring mongo_easy.yaml.')
    ..writeln('final mongoEasySchema = MongoEasySchema([');

  for (final collection in schema.collections.values) {
    buffer
      ..writeln('  MongoCollectionSchema(')
      ..writeln("    '${collection.name}',")
      ..writeln('    fields: {');
    for (final MapEntry(key: field, value: type) in collection.fields.entries) {
      buffer.writeln("      '$field': MongoFieldType.${type.name},");
    }
    buffer.writeln('    },');
    if (collection.ownerField != null) {
      buffer.writeln("    ownerField: '${collection.ownerField}',");
    }
    if (collection.shared) {
      buffer.writeln('    shared: true,');
    }
    buffer.writeln('  ),');
  }

  buffer.writeln(']);');
  return buffer.toString();
}
