// GENERATED by `dart run mongo_easy:setup` — do not edit.
// Source of truth: mongo_easy.yaml
import 'package:mongo_easy/mongo_easy.dart';

/// The app schema, mirroring mongo_easy.yaml.
final mongoEasySchema = MongoEasySchema([
  MongoCollectionSchema(
    'todos',
    fields: {
      'title': MongoFieldType.text,
      'done': MongoFieldType.bool,
      'created_at': MongoFieldType.datetime,
      'owner_id': MongoFieldType.text,
    },
    ownerField: 'owner_id',
  ),
]);
