import '../../schema/schema.dart';
import 'backend_core.dart';

/// Deployment targets for the generated write-upload backend.
enum BackendTarget {
  vercel('Vercel Functions', 'vercel'),
  supabase('Supabase Edge Functions', 'supabase'),
  cloudflare('Cloudflare Workers (experimental)', 'cloudflare');

  const BackendTarget(this.label, this.id);

  final String label;
  final String id;
}

/// Generates the backend project for [target]: relative path → file content.
Map<String, String> generateBackendFiles(
    MongoEasySchema schema, BackendTarget target) {
  return switch (target) {
    BackendTarget.vercel => _vercel(schema),
    BackendTarget.supabase => _supabase(schema),
    BackendTarget.cloudflare => _cloudflare(schema),
  };
}

const _envDocs = '''
| Variable | Required | Description |
|---|---|---|
| `MONGO_URI` | yes | MongoDB Atlas connection string (Database → Connect → Drivers). |
| `MONGO_DB` | yes | Database name to write to. |
| `AUTH_MODE` | no | `dev` (default, HS256 shared secret + /token endpoint) or `jwks` (production). |
| `JWT_SECRET` | dev mode | Shared HS256 secret — configure the SAME value in PowerSync (Instance → Client Auth → HS256). Min 32 chars. |
| `JWKS_URL` | jwks mode | Your auth provider's JWKS endpoint (Supabase/Firebase/Auth0). |
| `JWT_AUDIENCE` | no | Expected `aud` claim; use your PowerSync instance URL. |

**Security notes**
- The upload endpoint verifies the same JWT your app sends to PowerSync and
  enforces per-user ownership server-side (owner fields are assigned from the
  token, never trusted from the client).
- `AUTH_MODE=dev` exposes `/token`, which signs a JWT for any email — dev
  only. Switch to `AUTH_MODE=jwks` with a real auth provider before launch.
''';

Map<String, String> _vercel(MongoEasySchema schema) {
  final core = renderBackendCore(
    schema,
    imports: "import { MongoClient, ObjectId } from 'mongodb';\n"
        "import { jwtVerify, createRemoteJWKSet, SignJWT } from 'jose';",
  );

  return {
    'lib/core.ts': core,
    'api/upload.ts': '''
import { handleUpload, readEnv } from '../lib/core';

export async function POST(request: Request): Promise<Response> {
  return handleUpload(request, readEnv((key) => process.env[key]));
}
''',
    'api/token.ts': '''
import { handleToken, readEnv } from '../lib/core';

export async function POST(request: Request): Promise<Response> {
  return handleToken(request, readEnv((key) => process.env[key]));
}
''',
    'package.json': '''
{
  "name": "mongo-easy-backend",
  "private": true,
  "type": "module",
  "dependencies": {
    "jose": "^5.9.0",
    "mongodb": "^6.10.0"
  },
  "devDependencies": {
    "@types/node": "^20.0.0",
    "typescript": "^5.5.0"
  }
}
''',
    'tsconfig.json': '''
{
  "compilerOptions": {
    "target": "ES2022",
    "module": "ESNext",
    "moduleResolution": "bundler",
    "strict": true,
    "skipLibCheck": true,
    "noEmit": true
  },
  "include": ["api/**/*.ts", "lib/**/*.ts"]
}
''',
    'README.md': '''
# mongo_easy backend — Vercel

Generated by `dart run mongo_easy:setup`. Two endpoints:

- `POST /api/upload` — applies client writes to MongoDB (JWT-protected)
- `POST /api/token` — dev-only login (disabled when `AUTH_MODE=jwks`)

## Deploy

```bash
npm install
npx vercel deploy --prod
```

Then set the environment variables in the Vercel dashboard (or
`npx vercel env add <NAME>`), and redeploy:

$_envDocs

Your app's `uploadUrl` is `https://<project>.vercel.app/api/upload`;
the dev token endpoint is `https://<project>.vercel.app/api/token`.
''',
  };
}

Map<String, String> _supabase(MongoEasySchema schema) {
  final core = renderBackendCore(
    schema,
    imports: "import { MongoClient, ObjectId } from 'npm:mongodb@6';\n"
        "import { jwtVerify, createRemoteJWKSet, SignJWT } from 'npm:jose@5';",
  );

  return {
    'functions/_shared/core.ts': core,
    'functions/upload/index.ts': '''
import { handleUpload, readEnv } from '../_shared/core.ts';

Deno.serve((request) =>
  handleUpload(request, readEnv((key) => Deno.env.get(key))));
''',
    'functions/token/index.ts': '''
import { handleToken, readEnv } from '../_shared/core.ts';

Deno.serve((request) =>
  handleToken(request, readEnv((key) => Deno.env.get(key))));
''',
    'README.md': '''
# mongo_easy backend — Supabase Edge Functions

Generated by `dart run mongo_easy:setup`. Two functions:

- `upload` — applies client writes to MongoDB (JWT-protected)
- `token` — dev-only login (disabled when `AUTH_MODE=jwks`)

## Deploy

```bash
supabase functions deploy upload --no-verify-jwt
supabase functions deploy token --no-verify-jwt
```

(`--no-verify-jwt` is required: these functions verify the PowerSync JWT
themselves, which is not a Supabase-issued token unless you use Supabase
Auth.)

Set secrets:

```bash
supabase secrets set MONGO_URI='mongodb+srv://...' MONGO_DB=mydb \\
  AUTH_MODE=dev JWT_SECRET='<32+ char secret>' \\
  JWT_AUDIENCE='https://<instance>.powersync.journeyapps.com'
```

$_envDocs

Your app's `uploadUrl` is
`https://<project-ref>.supabase.co/functions/v1/upload`; the dev token
endpoint is `https://<project-ref>.supabase.co/functions/v1/token`.
''',
  };
}

Map<String, String> _cloudflare(MongoEasySchema schema) {
  final core = renderBackendCore(
    schema,
    imports: "import { MongoClient, ObjectId } from 'mongodb';\n"
        "import { jwtVerify, createRemoteJWKSet, SignJWT } from 'jose';",
  );

  return {
    'src/core.ts': core,
    'src/index.ts': '''
import { handleUpload, handleToken, type Env as CoreEnv } from './core';

interface WorkerEnv extends Record<string, string | undefined> {}

export default {
  async fetch(request: Request, env: WorkerEnv): Promise<Response> {
    const url = new URL(request.url);
    const coreEnv: CoreEnv = {
      MONGO_URI: env.MONGO_URI ?? '',
      MONGO_DB: env.MONGO_DB ?? '',
      AUTH_MODE: env.AUTH_MODE ?? 'dev',
      JWT_SECRET: env.JWT_SECRET,
      JWKS_URL: env.JWKS_URL,
      JWT_AUDIENCE: env.JWT_AUDIENCE,
    };
    if (url.pathname === '/upload') return handleUpload(request, coreEnv);
    if (url.pathname === '/token') return handleToken(request, coreEnv);
    return new Response('not found', { status: 404 });
  },
};
''',
    'wrangler.toml': '''
name = "mongo-easy-backend"
main = "src/index.ts"
compatibility_date = "2025-09-01"
compatibility_flags = ["nodejs_compat"]

# Set secrets with:
#   npx wrangler secret put MONGO_URI
#   npx wrangler secret put MONGO_DB
#   npx wrangler secret put JWT_SECRET
#   npx wrangler secret put JWT_AUDIENCE
''',
    'package.json': '''
{
  "name": "mongo-easy-backend",
  "private": true,
  "type": "module",
  "dependencies": {
    "jose": "^5.9.0",
    "mongodb": "^6.10.0"
  },
  "devDependencies": {
    "typescript": "^5.5.0",
    "wrangler": "^3.80.0"
  }
}
''',
    'README.md': '''
# mongo_easy backend — Cloudflare Workers (EXPERIMENTAL)

> ⚠️ The official `mongodb` Node driver on Workers relies on `nodejs_compat`
> and TCP sockets, which have limitations (e.g. TLS quirks, connection reuse
> across isolates). If you hit driver issues, prefer the Vercel or Supabase
> targets — same contract, one command to regenerate:
> `dart run mongo_easy:setup --target vercel`

Routes:

- `POST /upload` — applies client writes to MongoDB (JWT-protected)
- `POST /token` — dev-only login (disabled when `AUTH_MODE=jwks`)

## Deploy

```bash
npm install
npx wrangler deploy
npx wrangler secret put MONGO_URI
npx wrangler secret put MONGO_DB
npx wrangler secret put JWT_SECRET
npx wrangler secret put JWT_AUDIENCE
```

$_envDocs

Your app's `uploadUrl` is `https://<worker>.<account>.workers.dev/upload`;
the dev token endpoint is `https://<worker>.<account>.workers.dev/token`.
''',
  };
}
