import 'dart:convert';

import '../../schema/schema.dart';
import '../generate_streams.dart';
import 'backend_core.dart';

/// Generates a self-contained deployment: PowerSync service + upload backend
/// in one docker-compose, pointed at the user's own MongoDB. No third-party
/// accounts needed — runs anywhere Docker runs.
Map<String, String> generateSelfHostFiles(
  MongoEasySchema schema, {
  required String mongoUri,
  required String mongoDatabase,
  required String storageUri,
  required String jwtSecret,
}) {
  final jwtSecretB64 =
      base64Url.encode(utf8.encode(jwtSecret)).replaceAll('=', '');

  final backendCore = renderBackendCore(
    schema,
    imports: "import { MongoClient, ObjectId } from 'mongodb';\n"
        "import { jwtVerify, createRemoteJWKSet, SignJWT } from 'jose';",
  );

  return {
    'docker-compose.yaml': '''
name: mongo-easy

services:
  powersync:
    image: journeyapps/powersync-service:latest
    command: ["start", "-r", "unified"]
    restart: unless-stopped
    volumes:
      - ./powersync:/config
    environment:
      POWERSYNC_CONFIG_PATH: /config/service.yaml
      PS_MONGO_URI: \${MONGO_URI}
      PS_STORAGE_URI: \${STORAGE_URI}
      PS_JWT_K: \${JWT_SECRET_B64}
      NODE_OPTIONS: --max-old-space-size=1000
    healthcheck:
      test:
        [
          "CMD",
          "node",
          "-e",
          "fetch('http://localhost:8080/probes/liveness').then(r => r.ok ? process.exit(0) : process.exit(1)).catch(() => process.exit(1))",
        ]
      interval: 5s
      timeout: 1s
      retries: 15
    ports:
      - "\${POWERSYNC_PORT:-8080}:8080"

  backend:
    build: ./backend
    restart: unless-stopped
    environment:
      MONGO_URI: \${MONGO_URI}
      MONGO_DB: \${MONGO_DB}
      AUTH_MODE: \${AUTH_MODE:-dev}
      JWT_SECRET: \${JWT_SECRET}
      JWKS_URL: \${JWKS_URL:-}
      JWT_AUDIENCE: \${JWT_AUDIENCE}
      PORT: "3300"
    ports:
      - "\${BACKEND_PORT:-3300}:3300"
''',
    'powersync/service.yaml': '''
telemetry:
  disable_telemetry_sharing: true

replication:
  connections:
    - type: mongodb
      uri: !env PS_MONGO_URI
      post_images: auto_configure

storage:
  type: mongodb
  uri: !env PS_STORAGE_URI

port: 8080

sync_config:
  path: /config/sync-config.yaml

client_auth:
  jwks:
    keys:
      - kty: oct
        alg: HS256
        kid: mongo-easy-dev
        k: !env PS_JWT_K
  # Must match JWT_AUDIENCE in .env.
  audience: ["powersync-dev"]
''',
    'powersync/sync-config.yaml': generateSyncStreamsYaml(schema),
    'backend/core.ts': backendCore,
    'backend/server.ts': '''
import { createServer } from 'node:http';
import { handleToken, handleUpload, readEnv } from './core';

const env = readEnv((key) => process.env[key]);
const port = Number(process.env.PORT ?? 3300);

const server = createServer(async (req, res) => {
  const chunks: Buffer[] = [];
  for await (const chunk of req) chunks.push(chunk as Buffer);
  const body = Buffer.concat(chunks);

  const request = new Request(`http://localhost:\${port}\${req.url ?? '/'}`, {
    method: req.method,
    headers: Object.fromEntries(
      Object.entries(req.headers).map(([k, v]) => [k, String(v)]),
    ),
    body: body.length > 0 ? body : undefined,
  });

  let response: Response;
  if (req.url === '/upload') {
    response = await handleUpload(request, env);
  } else if (req.url === '/token') {
    response = await handleToken(request, env);
  } else if (req.url === '/health') {
    response = new Response('ok');
  } else {
    response = new Response('not found', { status: 404 });
  }

  res.writeHead(
    response.status,
    Object.fromEntries(response.headers.entries()),
  );
  res.end(Buffer.from(await response.arrayBuffer()));
});

server.listen(port, () => {
  console.log(`mongo_easy backend on :\${port}`);
});
''',
    'backend/package.json': '''
{
  "name": "mongo-easy-backend",
  "private": true,
  "type": "module",
  "scripts": {
    "start": "tsx server.ts"
  },
  "dependencies": {
    "jose": "^5.9.0",
    "mongodb": "^6.10.0",
    "tsx": "^4.19.0"
  }
}
''',
    'backend/Dockerfile': '''
FROM node:22-alpine
WORKDIR /app
COPY package.json ./
RUN npm install --omit=dev
COPY . .
EXPOSE 3300
CMD ["npm", "start"]
''',
    '.env': '''
# Generated by `dart run mongo_easy:setup --self-host`.
# KEEP THIS FILE SECRET — it contains your database credentials.

MONGO_URI=$mongoUri
MONGO_DB=$mongoDatabase
STORAGE_URI=$storageUri

# dev = HS256 + /token endpoint. Switch to jwks + JWKS_URL for production.
AUTH_MODE=dev
JWT_SECRET=$jwtSecret
JWT_SECRET_B64=$jwtSecretB64
JWT_AUDIENCE=powersync-dev
JWKS_URL=

POWERSYNC_PORT=8080
BACKEND_PORT=3300
''',
    'README.md': '''
# mongo_easy — self-hosted deployment

One `docker compose up` runs the entire mongo_easy backend against your own
MongoDB (Atlas or self-managed, **6.0+ with replica set** — all Atlas tiers
qualify, including free M0):

- **powersync** — the sync service (reads your MongoDB via change streams)
- **backend** — the write-upload + dev-token endpoint

## Run

```bash
docker compose up -d
```

Then point your app at this host:

```dart
MongoEasyConfig(
  powersyncUrl: 'http://<host>:8080',
  uploadUrl: 'http://<host>:3300/upload',
  ...
)
```

(`http://localhost` works in development; put both ports behind HTTPS — a
reverse proxy like Caddy or Traefik — before exposing to real devices.)

## Notes

- `.env` holds all secrets — never commit it.
- The PowerSync service stores its internal sync buckets in the
  `powersync_storage` database on the same cluster.
- Schema changes: edit `mongo_easy.yaml`, re-run
  `dart run mongo_easy:setup --self-host ...`, then
  `docker compose up -d --build` (sync config changes need a service
  restart).
- Production auth: set `AUTH_MODE=jwks` and `JWKS_URL` in `.env`, and swap
  the `client_auth` block in `powersync/service.yaml` to your provider's
  `jwks_uri`.
''',
  };
}
