import 'dart:convert';

import 'package:http/http.dart' as http;
import 'package:powersync/powersync.dart';

import '../auth/jwt_utils.dart';
import '../client/config.dart';
import '../errors.dart';
import 'upload_payload.dart';

/// Internal connector wiring PowerSync to the mongo_easy config: credentials
/// come from the app's [TokenProvider]; local writes are POSTed to the
/// generated upload endpoint.
class MongoEasyConnector extends PowerSyncBackendConnector {
  MongoEasyConnector(this._config, {http.Client? httpClient})
      : _http = httpClient ?? http.Client();

  final MongoEasyConfig _config;
  final http.Client _http;

  /// The `sub` claim of the most recent token — used for owner-field
  /// auto-fill.
  String? currentUserId;

  @override
  Future<PowerSyncCredentials?> fetchCredentials() async {
    final token = await _config.tokenProvider.getToken();
    if (token == null || token.isEmpty) {
      // Signed out: PowerSync stays disconnected; local data keeps working.
      currentUserId = null;
      return null;
    }

    final claims = decodeJwt(token);
    if (claims.isExpired) {
      throw InvalidTokenException(
        'The JWT returned by your TokenProvider is already expired '
        '(exp: ${claims.expiresAt}).',
        hint: 'Return a fresh token from TokenProvider — most auth SDKs '
            'refresh automatically when you read the current session.',
      );
    }

    currentUserId = claims.subject;
    return PowerSyncCredentials(
      endpoint: _config.powersyncUrl,
      token: token,
      userId: claims.subject,
      expiresAt: claims.expiresAt,
    );
  }

  @override
  Future<void> uploadData(PowerSyncDatabase database) async {
    final transaction = await database.getNextCrudTransaction();
    if (transaction == null) return;

    final token = await _config.tokenProvider.getToken();
    if (token == null || token.isEmpty) {
      throw const UploadException(
        'Cannot upload local writes: no auth token available.',
        hint: 'The user appears signed out with pending writes. They will '
            'upload automatically after the next sign-in.',
      );
    }

    final payload = buildUploadPayload(transaction);
    if (_config.logWrites) {
      // ignore: avoid_print
      print('[mongo_easy] uploading ${transaction.crud.length} ops: '
          '${jsonEncode(payload)}');
    }

    final http.Response response;
    try {
      response = await _http.post(
        Uri.parse(_config.uploadUrl),
        headers: {
          'Content-Type': 'application/json',
          'Authorization': 'Bearer $token',
        },
        body: jsonEncode(payload),
      );
    } on Object catch (error) {
      // Network failure — thrown so PowerSync retries with backoff.
      throw UploadException(
        'Could not reach the upload endpoint (${_config.uploadUrl}): $error',
        hint: 'Writes are safe in the local queue and retry automatically. '
            'If this persists, check the endpoint URL and that the backend '
            'is deployed.',
      );
    }

    if (response.statusCode == 401 || response.statusCode == 403) {
      invalidateCredentials();
      throw UploadException(
        'Upload endpoint rejected the token '
        '(HTTP ${response.statusCode}): ${_snippet(response.body)}',
        hint: 'The upload endpoint must accept the same JWTs as PowerSync. '
            'Check the JWT secret/JWKS configuration of your deployed '
            'backend function.',
        statusCode: response.statusCode,
      );
    }

    if (response.statusCode < 200 || response.statusCode >= 300) {
      throw UploadException(
        'Upload endpoint returned HTTP ${response.statusCode}: '
        '${_snippet(response.body)}',
        hint: 'Writes stay queued and retry automatically. A persistent '
            'non-2xx response blocks the queue — check the backend logs. '
            '(Backends generated by mongo_easy return 2xx for validation '
            'failures on purpose, so only infrastructure errors land here.)',
        statusCode: response.statusCode,
      );
    }

    await transaction.complete();
  }

  static String _snippet(String body) =>
      body.length <= 200 ? body : '${body.substring(0, 200)}…';
}
